{% set name = "jlsteenwyk-biokit" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: cb5e81122d0b1a5dbaed69d48d0ce3e98129ad003da8643747258ecf9abbfa04

build:
  noarch: python
  number: 0
  entry_points:
    - biokit = biokit.biokit:main
    - bk_alignment_length = biokit.biokit:alignment_length
    - bk_aln_len = biokit.biokit:alignment_length
    - bk_alignment_recoding = biokit.biokit:alignment_recoding
    - bk_aln_recoding = biokit.biokit:alignment_recoding
    - bk_recode = biokit.biokit:alignment_recoding
    - bk_alignment_summary = biokit.biokit:alignment_summary
    - bk_aln_summary = biokit.biokit:alignment_summary
    - bk_consensus_sequence = biokit.biokit:consensus_sequence
    - bk_con_seq = biokit.biokit:consensus_sequence
    - bk_constant_sites = biokit.biokit:constant_sites
    - bk_con_sites = biokit.biokit:constant_sites
    - bk_parsimony_informative_sites = biokit.biokit:parsimony_informative_sites
    - bk_pi_sites = biokit.biokit:parsimony_informative_sites
    - bk_pis = biokit.biokit:parsimony_informative_sites
    - bk_position_specific_score_matrix = biokit.biokit:position_specific_score_matrix
    - bk_pssm = biokit.biokit:position_specific_score_matrix
    - bk_variable_sites = biokit.biokit:variable_sites
    - bk_var_sites = biokit.biokit:variable_sites
    - bk_vs = biokit.biokit:variable_sites
    - bk_gc_content_first_position = biokit.biokit:gc_content_first_position
    - bk_gc1 = biokit.biokit:gc_content_first_position
    - bk_gc_content_second_position = biokit.biokit:gc_content_second_position
    - bk_gc2 = biokit.biokit:gc_content_second_position
    - bk_gc_content_third_position = biokit.biokit:gc_content_third_position
    - bk_gc3 = biokit.biokit:gc_content_third_position
    - bk_gene_wise_relative_synonymous_codon_usage = biokit.biokit:gene_wise_relative_synonymous_codon_usage
    - bk_gene_wise_rscu = biokit.biokit:gene_wise_relative_synonymous_codon_usage
    - bk_gw_rscu = biokit.biokit:gene_wise_relative_synonymous_codon_usage
    - bk_grscu = biokit.biokit:gene_wise_relative_synonymous_codon_usage
    - bk_relative_synonymous_codon_usage = biokit.biokit:relative_synonymous_codon_usage
    - bk_rscu = biokit.biokit:relative_synonymous_codon_usage
    - bk_translate_sequence = biokit.biokit:translate_sequence
    - bk_translate_seq = biokit.biokit:translate_sequence
    - bk_trans_seq = biokit.biokit:translate_sequence
    - bk_fastq_read_lengths = biokit.biokit:fastq_read_lengths
    - bk_fastq_read_lens = biokit.biokit:fastq_read_lengths
    - bk_subset_pe_fastq_reads = biokit.biokit:subset_pe_fastq_reads
    - bk_subset_pe_fastq = biokit.biokit:subset_pe_fastq_reads
    - bk_subset_se_fastq_reads = biokit.biokit:subset_se_fastq_reads
    - bk_subset_se_fastq = biokit.biokit:subset_se_fastq_reads
    - bk_trim_pe_adapters_fastq = biokit.biokit:trim_pe_adapters_fastq
    - bk_trim_pe_adapters_fastq_reads = biokit.biokit:trim_pe_adapters_fastq
    - bk_trim_pe_fastq = biokit.biokit:trim_pe_fastq
    - bk_trim_pe_fastq_reads = biokit.biokit:trim_pe_fastq
    - bk_trim_se_adapters_fastq = biokit.biokit:trim_se_adapters_fastq
    - bk_trim_se_adapters_fastq_reads = biokit.biokit:trim_se_adapters_fastq
    - bk_trim_se_fastq = biokit.biokit:trim_se_fastq
    - bk_trim_se_fastq_reads = biokit.biokit:trim_se_fastq
    - bk_gc_content = biokit.biokit:gc_content
    - bk_gc = biokit.biokit:gc_content
    - bk_genome_assembly_metrics = biokit.biokit:genome_assembly_metrics
    - bk_assembly_metrics = biokit.biokit:genome_assembly_metrics
    - bk_l50 = biokit.biokit:l50
    - bk_l90 = biokit.biokit:l90
    - bk_longest_scaffold = biokit.biokit:longest_scaffold
    - bk_longest_scaff = biokit.biokit:longest_scaffold
    - bk_longest_contig = biokit.biokit:longest_scaffold
    - bk_longest_cont = biokit.biokit:longest_scaffold
    - bk_n50 = biokit.biokit:n50
    - bk_n90 = biokit.biokit:n90
    - bk_number_of_large_scaffolds = biokit.biokit:number_of_large_scaffolds
    - bk_num_of_lrg_scaffolds = biokit.biokit:number_of_large_scaffolds
    - bk_number_of_large_contigs = biokit.biokit:number_of_large_scaffolds
    - bk_num_of_lrg_cont = biokit.biokit:number_of_large_scaffolds
    - bk_number_of_scaffolds = biokit.biokit:number_of_scaffolds
    - bk_num_of_scaffolds = biokit.biokit:number_of_scaffolds
    - bk_number_of_contigs = biokit.biokit:number_of_scaffolds
    - bk_num_of_cont = biokit.biokit:number_of_scaffolds
    - bk_sum_of_scaffold_lengths = biokit.biokit:sum_of_scaffold_lengths
    - bk_sum_of_contig_lengths = biokit.biokit:sum_of_scaffold_lengths
    - bk_character_frequency = biokit.biokit:character_frequency
    - bk_char_freq = biokit.biokit:character_frequency
    - bk_faidx = biokit.biokit:faidx
    - bk_get_entry = biokit.biokit:faidx
    - bk_ge = biokit.biokit:faidx
    - bk_file_format_converter = biokit.biokit:file_format_converter
    - bk_format_converter = biokit.biokit:file_format_converter
    - bk_ffc = biokit.biokit:file_format_converter
    - bk_multiple_line_to_single_line_fasta = biokit.biokit:multiple_line_to_single_line_fasta
    - bk_ml2sl = biokit.biokit:multiple_line_to_single_line_fasta
    - bk_remove_short_sequences = biokit.biokit:remove_short_sequences
    - bk_remove_short_seqs = biokit.biokit:remove_short_sequences
    - bk_remove_fasta_entry = biokit.biokit:remove_fasta_entry
    - bk_rename_fasta_entries = biokit.biokit:rename_fasta_entries
    - bk_rename_fasta = biokit.biokit:rename_fasta_entries
    - bk_reorder_by_sequence_length = biokit.biokit:reorder_by_sequence_length
    - bk_reorder_by_seq_len = biokit.biokit:reorder_by_sequence_length
    - bk_sequence_complement = biokit.biokit:sequence_complement
    - bk_seq_comp = biokit.biokit:sequence_complement
    - bk_sequence_length = biokit.biokit:sequence_length
    - bk_seq_len = biokit.biokit:sequence_length
    - bk_single_line_to_multiple_line_fasta = biokit.biokit:single_line_to_multiple_line_fasta
    - bk_sl2ml = biokit.biokit:single_line_to_multiple_line_fasta
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython ==1.76
    - cython
    - numpy ==1.18.2
    - pip
    - python
  run:
    - biopython ==1.76
    - cython
    - numpy ==1.18.2
    - python

test:
  imports:
    - biokit
    - biokit.helpers
    - biokit.services
    - biokit.services.alignment
    - biokit.services.coding_sequences
    - biokit.services.fastq
    - biokit.services.genome
    - biokit.services.text
  commands:
    - biokit --help
    - bk_alignment_length --help
    - bk_aln_len --help
    - bk_alignment_recoding --help
    - bk_aln_recoding --help
    - bk_recode --help
    - bk_alignment_summary --help
    - bk_aln_summary --help
    - bk_consensus_sequence --help
    - bk_con_seq --help
    - bk_constant_sites --help
    - bk_con_sites --help
    - bk_parsimony_informative_sites --help
    - bk_pi_sites --help
    - bk_pis --help
    - bk_position_specific_score_matrix --help
    - bk_pssm --help
    - bk_variable_sites --help
    - bk_var_sites --help
    - bk_vs --help
    - bk_gc_content_first_position --help
    - bk_gc1 --help
    - bk_gc_content_second_position --help
    - bk_gc2 --help
    - bk_gc_content_third_position --help
    - bk_gc3 --help
    - bk_gene_wise_relative_synonymous_codon_usage --help
    - bk_gene_wise_rscu --help
    - bk_gw_rscu --help
    - bk_grscu --help
    - bk_relative_synonymous_codon_usage --help
    - bk_rscu --help
    - bk_translate_sequence --help
    - bk_translate_seq --help
    - bk_trans_seq --help
    - bk_fastq_read_lengths --help
    - bk_fastq_read_lens --help
    - bk_subset_pe_fastq_reads --help
    - bk_subset_pe_fastq --help
    - bk_subset_se_fastq_reads --help
    - bk_subset_se_fastq --help
    - bk_trim_pe_adapters_fastq --help
    - bk_trim_pe_adapters_fastq_reads --help
    - bk_trim_pe_fastq --help
    - bk_trim_pe_fastq_reads --help
    - bk_trim_se_adapters_fastq --help
    - bk_trim_se_adapters_fastq_reads --help
    - bk_trim_se_fastq --help
    - bk_trim_se_fastq_reads --help
    - bk_gc_content --help
    - bk_gc --help
    - bk_genome_assembly_metrics --help
    - bk_assembly_metrics --help
    - bk_l50 --help
    - bk_l90 --help
    - bk_longest_scaffold --help
    - bk_longest_scaff --help
    - bk_longest_contig --help
    - bk_longest_cont --help
    - bk_n50 --help
    - bk_n90 --help
    - bk_number_of_large_scaffolds --help
    - bk_num_of_lrg_scaffolds --help
    - bk_number_of_large_contigs --help
    - bk_num_of_lrg_cont --help
    - bk_number_of_scaffolds --help
    - bk_num_of_scaffolds --help
    - bk_number_of_contigs --help
    - bk_num_of_cont --help
    - bk_sum_of_scaffold_lengths --help
    - bk_sum_of_contig_lengths --help
    - bk_character_frequency --help
    - bk_char_freq --help
    - bk_faidx --help
    - bk_get_entry --help
    - bk_ge --help
    - bk_file_format_converter --help
    - bk_format_converter --help
    - bk_ffc --help
    - bk_multiple_line_to_single_line_fasta --help
    - bk_ml2sl --help
    - bk_remove_short_sequences --help
    - bk_remove_short_seqs --help
    - bk_remove_fasta_entry --help
    - bk_rename_fasta_entries --help
    - bk_rename_fasta --help
    - bk_reorder_by_sequence_length --help
    - bk_reorder_by_seq_len --help
    - bk_sequence_complement --help
    - bk_seq_comp --help
    - bk_sequence_length --help
    - bk_seq_len --help
    - bk_single_line_to_multiple_line_fasta --help
    - bk_sl2ml --help

about:
  home: "https://github.com/jlsteenwyk/biokit"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: ""
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - JLSteenwyk
